name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Build
        run: npm run prod
      - name: Predeploy
        if: success() && github.ref == 'refs/heads/master'
        run: |
          # https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
          touch dist/.nojekyll
          # https://help.github.com/en/articles/managing-a-custom-domain-for-your-github-pages-site
          echo devlist.banano.cc > dist/CNAME
      - name: Deploy
        if: success() && github.ref == 'refs/heads/master'
        uses: maxheld83/ghpages@v0.3.0
        env:
          BUILD_DIR: dist/
          GH_PAT: ${{ secrets.GH_PAT }}
